version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mini-shop
    volumes:
      - ./:/var/www/html
    env_file:
      - .env
    depends_on:
      - db
    restart: unless-stopped

  web:
    image: nginx:1.27-alpine
    container_name: mini-shop
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    container_name: minishop-db
    ports:
      - "6543:5432"   # host 6543 -> container 5432 (matches your .env)
    environment:
      POSTGRES_USER: minishop
      POSTGRES_PASSWORD: secret123
      POSTGRES_DB: minishop
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: staffile-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  pgdata:

